@startuml
'https://plantuml.com/class-diagram

class StickyNote {
    + id: String
    + text: String
    + position: Position
    + color: YBColor
}

class SelectedNote {
    + noteId: String
    + userId: String
    + userName: String
}

hide empty members

@enduml